               
export const portafolios = [
  {
    id: 1,
    titulo: "To Do List",
    descripcion: "Tareas por hacer React",
    img: "../src/assets/images/portfolio/react-todolist.jpg",
    url_preview: "",
    url_github: "https://github.com/sbustilloc/To-do",
    className: 'grid-item mix all apps',
  },
 
  {
    id: 2,
    titulo: "Julio Francisco Salazar",
    descripcion: "Creación de Logo",
    img: "../src/assets/images/portfolio/clientes-jf.jpg",
    url_preview: "",
    url_github: "",
    className: "grid-item mix all graphic_design",
  },
  {
    id: 3,
    titulo: "Universidad Cristiana",
    descripcion: "Creación de Logo",
    img: "../src/assets/images/portfolio/clientes-ucristiana.jpg",
    url_preview: "",
    url_github: "",
    className: "grid-item mix all graphic_design",
  },
  {
    id: 4,
    titulo: "IGet",
    descripcion: "Creación de Logo",
    img: "../src/assets/images/portfolio/clientes-iget.jpg",
    url_preview: "",
    url_github: "",
    className: "grid-item mix all graphic_design",
  },
  {
    id: 5,
    titulo: "Mujeres Cultivando Campo",
    descripcion: "Creación de Logo, plataforma web, HTML, JavaScript, PHP, MySql",
    img: "../src/assets/images/portfolio/clientes-mujerescultivandocampo.jpg",
    url_preview: "https//mujerescultivandocampo.com",
    url_github: "",
    className: "grid-item mix all web_design",
  },
  {
    id: 6,
    titulo: "Vemp",
    descripcion: "Creación de Landing Page en WordPress y programa a la medida de compensaciones de nomina en PHP y MySql ",
    img: "../src/assets/images/portfolio/clientes-vemp.jpg",
    url_preview: "https//vempcta.com",
    url_github: "",
    className: "grid-item mix all web_design",
  },
  {
    id: 7,
    titulo: "Escuelas IADE Argentina",
    descripcion: "Creación de plataforma HTML5, CSS, Javascript, PHP y MySQL",
    img: "../src/assets/images/portfolio/clientes-iade.jpg",
    url_preview: "https//escuelasiadechile.cl",
    url_github: "",
    className: "grid-item mix all web_design",
  },
  {
    id: 8,
    titulo: "Servialiados del Caribe",
    descripcion: "Creación de sitio web en WordPress y programa de certificado y desprendibles",
    img: "../src/assets/images/portfolio/clientes-servialiadosdelcaribe.jpg",
    url_preview: "https://servialiados.com.co",
    url_github: "",
    className: "grid-item mix all web_design",
  },
  {
    id: 9,
    titulo: "Tactical Training",
    descripcion: "Creación de Logo",
    img: "../src/assets/images/portfolio/clientes-tacticaltraining.jpg",
    url_preview: "",
    url_github: "",
    className: "grid-item mix all graphic_design",
  },
  {
    id: 10,
    titulo: "Go Services - Panamá",
    descripcion: "Creación de Landing Page, HTML5, CSS",
    img: "../src/assets/images/portfolio/clientes-goservice.jpg",
    url_preview: "https://goservicepty.com/",
    url_github: "",
    className: "grid-item mix all web_design",
  },
  {
    id: 11,
    titulo: "Respect Life",
    descripcion: "Creación de Logo",
    img: "../src/assets/images/portfolio/clientes-respectlife.jpg",
    url_preview: "",
    url_github: "",
    className: "grid-item mix all graphic_design",
  },
  {
    id: 12,
    titulo: "See Models TV",
    descripcion: "Creación de Logo",
    img: "../src/assets/images/portfolio/clientes-seemodels.jpg",
    url_preview: "",
    url_github: "",
    className: "grid-item mix all graphic_design",
  },
  {
    id: 13,
    titulo: "Cristian Sierra",
    descripcion: "Creación de Logo",
    img: "../src/assets/images/portfolio/clientes-cristiansierra.jpg",
    url_preview: "",
    url_github: "",
    className: "grid-item mix all graphic_design",
  },
  
  {
    id: 14,
    titulo: "JF Consultorias Jurídicas",
    descripcion: "Creación de Logo",
    img: "../src/assets/images/portfolio/clientes-jfconsultorias.jpg",
    url_preview: "",
    url_github: "",
    className: "grid-item mix all graphic_design",
  },
  {
    id: 15,
    titulo: "A La Mesa Soft",
    descripcion: "Creacion de Programa para Restaurante, HTML5, CSS, PHP, MySQL",
    img: "../src/assets/images/portfolio/clientes-alamesasoft.jpg",
    url_preview: "",
    url_github: "",
    className: "grid-item mix all photography",
  },
  {
    id: 16,
    titulo: "Cooperativa Coopsin",
    descripcion: "Creacion de Programa para cooperativa, Recursos Humanos, Nomina, Contabilidad, entre otros, HTML5, CSS, PHP, MySQL",
    img: "../src/assets/images/portfolio/clientes-coopsin.jpg",
    url_preview: "",
    url_github: "",
    className: "grid-item mix all photography",
  },
  {
    id: 17,
    titulo: "Cendri SAS",
    descripcion: "Creacion de Programa para IPS, Citas, Historias Clinicas, Rips, entre otros, HTML5, CSS, PHP, MySQL",
    img: "../src/assets/images/portfolio/clientes-cendri.jpg",
    url_preview: "",
    url_github: "",
    className: "grid-item mix all photography",
  },
  {
    id: 18,
    titulo: "Alcaldia de Tenjo",
    descripcion: "Creacion de Programa para ingreso de casos de violencia en el contexto familiar, entre otros, HTML5, CSS, PHP, MySQL",
    img: "../src/assets/images/portfolio/clientes-tenjoatento.jpg",
    url_preview: "",
    url_github: "",
    className: "grid-item mix all photography",
  },
];
